apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        #securityContext:
          #allowPrivilegeEscalation: true
          #capabilities:
          #  add: ["AUDIT_CONTROL"]
          #privileged: true
          #readOnlyRootFilesystem: false        
        image: redis:7-alpine
        ports:
        - name: redis-server
          containerPort: 6379
